/* const PREFIX = 'Example/';

export const GET_FILTERS_REQUEST = `${PREFIX}GET_FILTERS_REQUEST`;
export const GET_FILTERS_SUCCESS = `${PREFIX}GET_FILTERS_SUCCESS`;
export const GET_FILTERS_ERROR = `${PREFIX}GET_FILTERS_ERROR`;
*/
