const PREFIX = 'Pokemon/';

export const GET_POKEMONS_REQUEST = `${PREFIX}GET_POKEMONS_REQUEST`;
export const GET_POKEMONS_SUCCESS = `${PREFIX}GET_POKEMONS_SUCCESS`;
export const GET_POKEMONS_ERROR = `${PREFIX}GET_POKEMONS_ERROR`;
